
package com.neo4j.perf;

public enum PerfConstants {
	AUTHORIZE_ORG, AUTHORIZE_CLASS, AUTHORIZE_ASSET, AUTHORIZE_CONTRACT, AUTHORIZE_CONTRACTTYPE, AUTHORIZE_ADU, AUTHORIZE_PRINCIPAL, AUTHORIZE_SCRIPT, GET_ASSET_BY_ORG, CREATE_INDEX, AUTHORIZE_PRODUCT_CLASS, AUTHORIZE_EVENTS, AUTHORIZE_DATA_ITEM, GET_DATA_ITEM, GET_ORG_AND_ASSETS, GET_DI_CLASSES, GET_ALL_ASSETS, IS_AUTHORIZED, GET_CONTARCT_VERTEX, GET_ASSET_BY_PRODUCT, AUTHORIZE_MASHUP, GET_ASSET_BY_CLASS, HAVE_CHILDREN, GET_ASSETS_BY_USER;
}
